name: YouTube to Text Transcriber

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "YouTube Video URL"
        required: true

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install pytube openai-whisper

      - name: Download YouTube Audio using Pytube
        run: |
           python download_audio.py "${{ github.event.inputs.video_url }}"
      - name: Upload Downloaded Audio
        uses: actions/upload-artifact@v4
        with:
          name: downloaded_audio
          path: downloads/downloaded_audio.mp3


      
