name: YouTube to Text Transcriber

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "YouTube Video URL"
        required: true

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg yt-dlp
          pip install openai-whisper

      - name: Retrieve Cookies from Secret
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Download YouTube Audio
        run: |
          mkdir -p downloads
          yt-dlp -x --audio-format mp3 --cookies cookies.txt -o "downloads/downloaded_audio.mp3" "${{ github.event.inputs.video_url }}"

      - name: Transcribe Audio with Whisper
        run: |
          whisper "downloads/downloaded_audio.mp3" --language English --output_dir "downloads" --output_format txt

      - name: Upload Audio & Transcription
        uses: actions/upload-artifact@v4
        with:
          name: transcription_results
          path: downloads/
